# Generated by Django 4.2.5 on 2023-09-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company_name', models.CharField(max_length=100)),
                ('company_reg_number', models.CharField(max_length=50)),
                ('company_address', models.CharField(max_length=150)),
                ('contact_person', models.CharField(max_length=50)),
                ('departments', models.CharField(max_length=300)),
                ('contact_phone', models.CharField(max_length=50)),
                ('number_of_employees', models.CharField(max_length=50)),
                ('company_email', models.EmailField(max_length=100)),
            ],
        ),
    ]
