# Generated by Django 4.2.5 on 2023-09-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talentsystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_department', models.CharField(max_length=100)),
                ('employee_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=150)),
                ('date_started', models.CharField(max_length=50)),
                ('date_left', models.CharField(max_length=50)),
                ('dutie', models.CharField(max_length=300)),
            ],
        ),
    ]
