# Generated by Django 4.2.5 on 2023-09-10 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talentsystem', '0002_departmentsrecord_employeerecord'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DepartmentsRecord',
            new_name='DepartmentRecord',
        ),
    ]
