# Generated by Django 4.2.5 on 2023-09-11 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talentsystem', '0003_rename_departmentsrecord_departmentrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departmentrecord',
            old_name='Company_department',
            new_name='department_name',
        ),
        migrations.RemoveField(
            model_name='departmentrecord',
            name='employee_number',
        ),
    ]
