# Generated by Django 4.2.5 on 2023-09-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talentsystem', '0004_rename_company_department_departmentrecord_department_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyrecord',
            name='bulk',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
