# Generated by Django 4.2.5 on 2023-09-11 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talentsystem', '0005_companyrecord_bulk'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentrecord',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='talentsystem.companyrecord'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companyrecord',
            name='bulk',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='employeerecord',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talentsystem.departmentrecord'),
        ),
    ]
