# Generated by Django 4.1.1 on 2023-11-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talentsystem', '0006_departmentrecord_company_alter_companyrecord_bulk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentrecord',
            name='company',
            field=models.ForeignKey(on_delete=models.SET('deleted'), to='talentsystem.companyrecord'),
        ),
        migrations.AlterField(
            model_name='employeerecord',
            name='department',
            field=models.ForeignKey(on_delete=models.SET('deleted'), to='talentsystem.departmentrecord'),
        ),
    ]
