# Generated by Django 4.1.1 on 2023-11-22 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talentsystem', '0007_alter_departmentrecord_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentrecord',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='talentsystem.companyrecord'),
        ),
        migrations.AlterField(
            model_name='employeerecord',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='talentsystem.departmentrecord'),
        ),
    ]
